export const FETCH_SERIAL_START = 'FETCH_SERIAL_START';
export const FETCH_SERIAL_FAIL = 'FETCH_SERIAL_FAIL';
export const FETCH_SERIAL_SUCCESS = 'FETCH_SERIAL_SUCCESS';

export const FETCH_CURRENT_SERIAL_START = 'FETCH_CURRENT_SERIAL_START';
export const FETCH_CURRENT_SERIAL_FAIL = 'FETCH_CURRENT_SERIAL_FAIL';
export const FETCH_CURRENT_SERIAL_SUCCESS = 'FETCH_CURRENT_SERIAL_SUCCESS';
